version: "3"
services:
  pyspark:
    image: "jupyter/pyspark-notebook"
    volumes:
      - CURRENT_PATH:/home/jovyan # modify the local path to your current working directory
    ports:
      - 8888:8888